In [31]:
import numpy as np
a = np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [32]:
a.ndim

2

In [33]:
a.dtype

dtype('int32')

In [34]:
# 加法
a = np.array([i+1 for i in range(5)])
b = a + 2
print(b)

[3 4 5 6 7]


In [35]:
# b数组求方
b ** 3

array([ 27,  64, 125, 216, 343], dtype=int32)

In [36]:
# 矩阵加法
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [2, 1]])
c = a + b
print(c)

[[2 4]
 [5 5]]


In [37]:
# 矩阵减法
c = a - b
print(c)

[[0 0]
 [1 3]]


In [38]:
# 矩阵对应元素相乘
c = a * b
print(c)

[[1 4]
 [6 4]]


In [39]:
# 矩阵乘法
np.dot(a, b)

array([[ 5,  4],
       [11, 10]])

In [40]:
# (2) 数据索引和切片
# 随机生成一维数组
a = np.random.randint(low=1, high=20, size=5)
a

array([ 3,  5, 14,  1, 13])

In [41]:
# 获取一维数组a中索引为2~3的元素
a[2:4]

array([14,  1])

In [42]:
# 随机生成二维数组a
a = np.random.randint(low=1, high=20, size=(5, 5))
a

array([[10, 19,  2, 10,  2],
       [16, 14,  5, 11,  5],
       [18,  1, 14, 15,  2],
       [ 9,  1, 17,  3,  1],
       [ 3,  2,  9,  2, 11]])

In [43]:
# 第2~4行的第二列元素
a[2:5, 2]

array([14, 17,  9])

In [44]:
# a的1~2行，输出所有列
a[1:3, ]

array([[16, 14,  5, 11,  5],
       [18,  1, 14, 15,  2]])

In [45]:
# a的1~3行，2~3列切片并赋值给b
b = a[1:4, 2:4]
b

array([[ 5, 11],
       [14, 15],
       [17,  3]])

In [46]:
# 改变数组形状
a = np.random.randint(low=1, high=20, size=9)
a

array([ 2, 11,  3, 11, 11, 16, 12,  8, 19])

In [49]:
b = a.reshape(3, 3)
b

array([[ 2, 11,  3],
       [11, 11, 16],
       [12,  8, 19]])

In [51]:
# 矩阵拼接
a = np.random.randint(low=1, high=20, size=(3, 3))
b = np.random.randint(low=1, high=20, size=(3, 3))
# 垂直拼接
np.vstack((a, b))

array([[17,  2, 10],
       [ 8,  9, 14],
       [14, 19, 18],
       [13, 11,  8],
       [ 9, 13,  7],
       [ 4,  3,  6]])

In [52]:
# 水平拼接
np.hstack((a, b))

array([[17,  2, 10, 13, 11,  8],
       [ 8,  9, 14,  9, 13,  7],
       [14, 19, 18,  4,  3,  6]])

In [55]:
# (4) 统计运算
a = np.random.randint(low=1, high=20, size=(2, 3))
a

array([[13, 17, 17],
       [16, 10,  3]])

In [58]:
# 最小值
a.min()

3

In [59]:
# 最大值
a.max()

17

In [60]:
# 均值
a.mean()

12.666666666666666

In [61]:
# 求和
a.sum()

76

In [63]:
# 标准差
a.std()

4.988876515698588

In [65]:
# 每列最大值
np.amax(a, axis=0)

array([16, 17, 17])

In [66]:
# 每行最小值
np.amin(a, axis=1)

array([13,  3])

In [67]:
# 每行标准差
np.std(a, axis=1)

array([1.88561808, 5.31245915])

In [68]:
# 每列方差
np.var(a, axis=0)

array([ 2.25, 12.25, 49.  ])

In [69]:
# (5) 数组排序
a = np.random.randint(low=1, high=20, size=(3,3))
a

array([[16,  4, 10],
       [11, 17,  3],
       [10,  7, 13]])

In [70]:
# 默认按行(hang)进行排序
np.sort(a)

array([[ 4, 10, 16],
       [ 3, 11, 17],
       [ 7, 10, 13]])

In [71]:
# 按列排序
np.sort(a, axis=0)

array([[10,  4,  3],
       [11,  7, 10],
       [16, 17, 13]])

In [72]:
# 现有3列属性，分别为id、salary和age
schema = [('id', int),('salary',int),('age',int)]
# 3条记录
records = [(1, 3000, 21), (2, 5000, 30), (3, 8000, 38)]

In [73]:
# 创建numpy数组
a = np.array(records, dtype=schema)
a

array([(1, 3000, 21), (2, 5000, 30), (3, 8000, 38)],
      dtype=[('id', '<i4'), ('salary', '<i4'), ('age', '<i4')])

In [75]:
# 将数组按照salary进行排序
np.sort(a, order='salary')

array([(1, 3000, 21), (2, 5000, 30), (3, 8000, 38)],
      dtype=[('id', '<i4'), ('salary', '<i4'), ('age', '<i4')])